#ifndef COMMON_H
#define COMMON_H

#define LOCAL_IP "127.0.0.1"
#define HOST_IP "10.42.0.1"
// #define CLIENT_IP "10.42.0.12"
#define CLIENT_IP "10.42.0.45"

#define WIFI_IMAGE_PORT 8080
#define WIFI_POINT_CLOUD_PORT 8081
#define WIFI_ROVER_COMMANDS_PORT 8082
#define WIFI_ROVER_STATUS_PORT 8083
#define WIFI_CAMERA_LOCATION_PORT 8084

#define IMAGE_WIDTH 640
#define IMAGE_HEIGHT 480
#define IMAGE_CHANNEL_DEPTH 3

#define POINT_CLOUD_WIDTH 640
#define POINT_CLOUD_HEIGHT 480
#define POINT_CLOUD_CHANNEL_DEPTH 24

#define IMAGE_BUFFER_SIZE (IMAGE_WIDTH * IMAGE_HEIGHT * IMAGE_CHANNEL_DEPTH)
#define POINT_CLOUD_BUFFER_SIZE (POINT_CLOUD_WIDTH * POINT_CLOUD_HEIGHT * POINT_CLOUD_CHANNEL_DEPTH)
#define ROVER_STATUS_BUFFER_SIZE 200
#define ROVER_COMMANDS_BUFFER_SIZE 200
#define CAMERA_POSITION_BUFFER_SIZE 400

#define MAX_PACKET_SIZE 1400

#define IMAGE_FEED_PRIORITY 5
#define POINT_CLOUD_PRIORITY 3
#define ROVER_COMMANDS_PRIORITY 6
#define ROVER_STATUS_PRIORITY 0
#define CAMERA_POSITION_PRIORITY 3

#define IMAGE_DEBUG 0
#define POINT_CLOUD_DEBUG 0
#define STATUS_DEBUG 0
#define COMMANDS_DEBUG 0
#define POISITON_DEBUG 0 

#endif
