#!/bin/bash
### BEGIN INIT INFO
# Provides:             runcomms
# Required-Start:       $all
# Required-Stop:        
# Default-Start:        2 3 4 5
# Default-Stop:         
# Short-Description:    Runs Teensy 4.1 Comms
### END INIT INFO

#^ needed for commands to enable script 
# https://askubuntu.com/questions/909523/default-start-contains-no-runlevels-aborting

# https://unix.stackexchange.com/questions/20357/how-can-i-make-a-script-in-etc-init-d-start-at-boot
# chkconfig: 2345 20 80
# description: runs comms script between jetson and teensy
# 2345 means script should be started at levels 2, 3, 4 and 5. 
# 20 is the start priority
# 80 is the stop prioirty


start() {
    sudo python3 /home/seniordesign/senior_design/firmware/desktop/comms.py
}

stop() {
    kill $(pgrep -f 'python3 comms.py')
}

main() {
    echo "$1"
    case "$1" in
        start)
            start
            ;;
        stop)
            stop
            ;;
        restart)
            stop
            start
            ;;
        status)
            echo "not implemented"
            ;;
        # default
        *)
            echo "usage: $0 {start|stop|restart|status}"
    esac
    exit 0

}

# call main passing in the arg to the script to main
main $1
